otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  anyHost:
    attributes:
      host.name: anyHost
      host.type: windows
    protocols:
      wmi:
        username: username
        password: password
        timeout: 300
    connectors: ["+WindowsIpmiTool"]