#MetricsHub Configuration
otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: linux
    protocols:
      jmx:
        timeout: 120
        port: 7199
    connectors: [ +Cassandra ]