otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: anyHost
      host.type: oob
    protocols:
      ipmi:
        username: username
        password: password
        timeout: 300
    connectors: ["+IpmiTool"]