otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: src/main/connector
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: linux
    protocols:
      ssh:
        username: user
        password: pass
        timeout: 300
    additionalConnectors:
      LinuxFile:
        uses: LinuxFile
        variables:
          matchPath: "/opt/metricshub/lib/logs/*,/opt/metricshub/config/metricshub.yaml"
          contentPattern: "Exception|Error|Failed"