otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  anyHost:
    attributes:
      host.name: anyHost
      host.type: linux
    protocols:
      ssh:
        username: user
        password: pwd
        timeout: 300
    connectors: ["+LinuxIpmiTool"]